const {
	sample
} = require("../helpers")

module.exports = () => {
	return (
		sample([
			"Planned Parenthood in ",
			"At a Planned Parenthood at ",
			"They got it at Planned Parenthood at ",
			"It was at ",
			"At the clinic in ",
			"The clinic is ",
			"",
			"Clinic is located at ",
			"The address to the clinic was ",
		]) +
		sample([
			"San Antonio",
			"Lower Rio Grande Valley",
			"Harlingen",
			"Northeast",
			"Southeast",
			`Brownsville 870 E. Alton Gloor Blvd. Brownsville, TX 78526`,
			`Harlingen 712 North 77 Sunshine Strip, Ste. 18 Harlingen, TX  78550`,
			`San Pedro (Abortion & Primary Care) 921 San Pedro Ave. Ste. 150 San Antonio, TX 78212`,
			`Northeast 11514 Perrin-Beitel Rd. San Antonio, TX 78217`,
			`Marbach 8725 Marbach Rd. San Antonio, TX 78227`,
			`Southeast 7022 S. New Braunfels Ave. Ste. 103 San Antonio, TX 78223`,
			`Babcock (Medical Center) 2140 Babcock Rd. San Antonio, TX 78229`,
			'1 Berkshire Ave.',
                        '10 Grant Dr.',
                        '104 W. Monroe Street',
                        '106 Second Rd.',
                        '11 2nd Lane',
                        '11 Constitution Ave.',
                        '11 Stonybrook St.',
                        '11 William St.',
                        '12 Overlook St.',
                        '121 Manor St.',
                        '13 Tailwater Ave.',
                        '133 Cactus St.',
                        '133 Taylor Street',
                        '136 Dogwood Court',
                        '14 Newcastle St.',
                        '14 West Blue Spring St.',
                        '143 South Central Rd.',
                        '156 Silver Spear Ave.',
                        '16 Oakland Drive',
                        '17 Main St.',
                        '17 Shipley Rd.',
                        '172 Fairground Street',
                        '178 Mayfair St.',
                        '18 S. Roberts Drive',
                        '182 Mill Lane',
                        '227 Wellington St.',
                        '239 Woodsman Ave.',
                        '24 E. Leeton Ridge Court',
                        '244 Gregory Road',
                        '246 Ridgewood St.',
                        '246 Tanglewood Ave.',
                        '258 Canal Street',
                        '265 Blue Spring Lane',
                        '267 Pearl St.',
                        '27 East Crescent Ave.',
                        '272 Courtland Drive',
                        '278 Sage Street',
                        '28 Rockledge Dr.',
                        '285 Tarkiln Hill St.',
                        '29 Princess Rd.',
                        '302 Lakewood Ave.',
                        '303 Valley View Rd.',
                        '303 Windfall Street',
                        '31 Gonzales St.',
                        '324 West Clinton Street',
                        '339 East Bridge Ave.',
                        '34 Middle River St.',
                        '34 Rose Street',
                        '35 North Santa Clara Ave.',
                        '351 Sutor Avenue',
                        '36 Catherine Road',
                        '36 Cobblestone St.',
                        '362 SE. La Sierra St.',
                        '37 Deerfield Street',
                        '373 Foster St.',
                        '39 Academy Street',
                        '39 Corona St.',
                        '397 SW. Golf St.',
                        '398 Bear Hill Street',
                        '4 Ohio Avenue',
                        '4 Philmont Street',
                        '4 Spring Street',
                        '40 N. River Drive',
                        '402 Meadowbrook St.',
                        '406 North Johnson Drive',
                        '41 Cleveland Street',
                        '411 E. Sugar St.',
                        '42 Talbot Drive',
                        '420 Eagle Lane',
                        '421 SW. Sunbeam Drive',
                        '43 San Juan Avenue',
                        '44 Hamilton Dr.',
                        '444 Kingston Drive',
                        '448 Redwood St.',
                        '453 Lookout Ave.',
                        '463 East Nut Swamp Street',
                        '472 West Bohemia Road',
                        '48 Middle River Ave.',
                        '488 East Pineknoll Rd.',
                        '49 Chapel Avenue',
                        '49 Fairfield Street',
                        '491 Cleveland Lane',
                        '494 Pendergast Dr.',
                        '496 Orchard Drive',
                        '499 Shore St.',
                        '5 South Forest St.',
                        '50 East Cactus Drive',
                        '501 West Talbot St.',
                        '51 North Grove Street',
                        '51 Trenton Dr.',
                        '513 Court Dr.',
                        '523 S. Oxford Ave.',
                        '527 Sutor Street',
                        '534 Wild Horse Street',
                        '542 Cypress Ave.',
                        '56 South Marsh Lane',
                        '560 Howard Ave.',
                        '572 Windsor Drive',
                        '574 Arcadia St.',
                        '574 Spring Lane',
                        '58 Atlantic Dr.',
                        '588 Windfall Drive',
                        '59 Charles Street',
                        '6 Military Ave.',
                        '6 Temple Lane',
                        '60 Atlantic Drive',
                        '60 Lakewood Court',
                        '604 Blackburn St.',
                        '604 East Dunbar Rd.',
                        '61 Miles St.',
                        '613 Swanson St.',
                        '617 Walnut St.',
                        '622 Ridgewood St.',
                        '624 Annadale Street',
                        '624 San Carlos Ave.',
                        '63 Carriage Street',
                        '63 Cypress Drive',
                        '64 Lantern Road',
                        '64 NE. Sage St.',
                        '646 Arlington Lane',
                        '65 E. Bridgeton Drive',
                        '65 Glenridge Street',
                        '66 Linden Drive',
                        '66 S. Spring St.',
                        '669 Indian Summer Street',
                        '69 Edgewater St.',
                        '691 NW. Wilson St.',
                        '693 Newcastle Dr.',
                        '694 Bradford St.',
                        '696 Lake Rd.',
                        '7 Oakwood Drive',
                        '7012 Bay Meadows Drive',
                        '7019 Beech St.',
                        '7086 Carson Rd.',
                        '71 Manor Ave.',
                        '7110 Pendergast Drive',
                        '7112 Eagle Drive',
                        '7113 Lantern Ave.',
                        '7128 8th Ave.',
                        '713 George Drive',
                        '7168 North Marvon Ave.',
                        '7192 East Sunnyslope Street',
                        '73 Valley Farms Dr.',
                        '732 Applegate Ave.',
                        '738 53rd Ave.',
                        '7384 Greenrose Dr.',
                        '74 W. Silver Spear Ave.',
                        '7415 Proctor Lane',
                        '7428 Colonial Ave.',
                        '743 Bridgeton Court',
                        '7481 High Ridge Avenue',
                        '7565 Nichols Street',
                        '76 Miles St.',
                        '762 Trenton Drive',
                        '7665 Carpenter St.',
                        '7668 Walnutwood Drive',
                        '7671 Dogwood St.',
                        '7691 Glen Creek Ave.',
                        '77 Rockaway St.',
                        '7720 Studebaker St.',
                        '7729 Glen Creek Drive',
                        '773 S. Princeton St.',
                        '7731 Brown Ave.',
                        '7758 Griffin Street',
                        '7767 South Mulberry Road',
                        '78 Van Dyke Drive',
                        '7809 Durham Avenue',
                        '7849 Halifax Street',
                        '79 Bradford Lane',
                        '7906 Rose St.',
                        '7963 Silver Spear St.',
                        '8 Cedar St.',
                        '8 Galvin Court',
                        '80 Ann St.',
                        '801 Morris Rd.',
                        '8021 Bridgeton Dr.',
                        '8048 Mechanic Ave.',
                        '8059 Summer St.',
                        '806 Wood Dr.',
                        '8066 South Randall Mill Ave.',
                        '8067 Ridgeview Avenue',
                        '809 East Sleepy Hollow Ave.',
                        '8143 Cardinal Circle',
                        '8155 Fawn St.',
                        '82 Manchester Street',
                        '822 Lantern Road',
                        '8256 Maple St.',
                        '828 Mammoth Road',
                        '83 E. Oxford Avenue',
                        '83 Marvon Street',
                        '83 Smoky Hollow Dr.',
                        '8324 Green Lake St.',
                        '8325 Victoria St.',
                        '833 Wagon Ave.',
                        '838 Birchwood Road',
                        '8384 Wakehurst St.',
                        '84 Clinton St.',
                        '841 Oklahoma Lane',
                        '841 San Pablo St.',
                        '844 Walnut Drive',
                        '8448 E. Devon Street',
                        '8452 Arrowhead St.',
                        '8472 Ridge Dr.',
                        '85 Theatre Street',
                        '8507 Old Ann Drive',
                        '858 Union Ave.',
                        '8651 Rockcrest Street',
                        '8680 E. Victoria Drive',
                        '87 Squaw Creek Street',
                        '8706 Poplar St.',
                        '8730 Tailwater Avenue',
                        '8764 Garden Ave.',
                        '8777 E. Orchard St.',
                        '88 SE. Mill Pond Street',
                        '8851 Carson Street',
                        '8875 Grant Lane',
                        '895 W. Washington Avenue',
                        '9 Crescent Dr.',
                        '90 Green Lane',
                        '9023 Kirkland Street',
                        '9037 Marconi Ave.',
                        '9069 Ramblewood St.',
                        '9102 W. Roehampton Lane',
                        '915 Shady Ave.',
                        '9189 Edgewater Rd.',
                        '9239 Laurel St.',
                        '9254 Leeton Ridge Lane',
                        '9258 8th St.',
                        '9272 South Grand Street',
                        '9280 Walt Whitman Ave.',
                        '929 Highland Ave.',
                        '93 Walt Whitman St.',
                        '9304 Dogwood Circle',
                        '9307 San Juan Lane',
                        '9315 East Hartford St.',
                        '934 E. Linda Ave.',
                        '94 Bedford St.',
                        '94 Meadowbrook Ave.',
                        '94 Saxon Drive',
                        '9420 West Bayberry Drive',
                        '9431 Pine St.',
                        '9432 Orchard St.',
                        '9449 Wrangler St.',
                        '945 Clark Street',
                        '95 Court Ave.',
                        '95 W. Smith Store Lane',
                        '95 Willow Ave.',
                        '9500 Pacific Ave.',
                        '9512 Elm Drive',
                        '9590 North 8th St.',
                        '96 Oak Street',
                        '9639 Fulton St.',
                        '966 Fifth Ave.',
                        '966 North Poor House Dr.',
                        '97 Meadow Lane',
                        '9700 Winchester Dr.',
                        '9701 Walnutwood St.',
                        '974 Prairie St.',
                        '9743 Brandywine Dr.',
                        '975 Hanover St.',
                        '9766 Riverview Court',
                        '9785 North Fairground Dr.',
                        '98 Forest St.',
                        '9841 Victoria Street',
                        '987 Dunbar St.',
                        '9871 Illinois Dr.',
                        '988 Sugar Drive',
                        '9883 North Oak Street',
                        '9902 Pleasant Drive',
                        '9916 Windsor Avenue',
                        '9922 East Central Street',
                        '9925 Eagle Rd.',
                        '9928 Meadow Ave.',
                        '9989 Lake Street'
		])
	)
}
